# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_neuron.ui'
#
# Created: Wed Jun 29 19:48:09 2011
#      by: pyside-uic 0.2.10 running on PySide 1.0.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AddNeuronDialog(object):
    def setupUi(self, AddNeuronDialog):
        AddNeuronDialog.setObjectName("AddNeuronDialog")
        AddNeuronDialog.resize(182, 231)
        AddNeuronDialog.setModal(True)
        self.lo_vert0 = QtGui.QVBoxLayout(AddNeuronDialog)
        self.lo_vert0.setObjectName("lo_vert0")
        self.lo_form0_2 = QtGui.QFormLayout()
        self.lo_form0_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.lo_form0_2.setObjectName("lo_form0_2")
        self.lbl_position = QtGui.QLabel(AddNeuronDialog)
        self.lbl_position.setObjectName("lbl_position")
        self.lo_form0_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_position)
        self.edt_position = QtGui.QLineEdit(AddNeuronDialog)
        self.edt_position.setText("")
        self.edt_position.setObjectName("edt_position")
        self.lo_form0_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.edt_position)
        self.lbl_orientation = QtGui.QLabel(AddNeuronDialog)
        self.lbl_orientation.setObjectName("lbl_orientation")
        self.lo_form0_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_orientation)
        self.edt_orientation = QtGui.QLineEdit(AddNeuronDialog)
        self.edt_orientation.setText("")
        self.edt_orientation.setObjectName("edt_orientation")
        self.lo_form0_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.edt_orientation)
        self.lbl_data = QtGui.QLabel(AddNeuronDialog)
        self.lbl_data.setObjectName("lbl_data")
        self.lo_form0_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_data)
        self.cb_data = QtGui.QComboBox(AddNeuronDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_data.sizePolicy().hasHeightForWidth())
        self.cb_data.setSizePolicy(sizePolicy)
        self.cb_data.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cb_data.setObjectName("cb_data")
        self.lo_form0_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.cb_data)
        self.lbl_frate = QtGui.QLabel(AddNeuronDialog)
        self.lbl_frate.setObjectName("lbl_frate")
        self.lo_form0_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl_frate)
        self.edt_frate = QtGui.QLineEdit(AddNeuronDialog)
        self.edt_frate.setText("")
        self.edt_frate.setObjectName("edt_frate")
        self.lo_form0_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.edt_frate)
        self.lbl_ampl = QtGui.QLabel(AddNeuronDialog)
        self.lbl_ampl.setObjectName("lbl_ampl")
        self.lo_form0_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbl_ampl)
        self.edt_ampl = QtGui.QLineEdit(AddNeuronDialog)
        self.edt_ampl.setText("")
        self.edt_ampl.setObjectName("edt_ampl")
        self.lo_form0_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.edt_ampl)
        self.lbl_cluster = QtGui.QLabel(AddNeuronDialog)
        self.lbl_cluster.setObjectName("lbl_cluster")
        self.lo_form0_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.lbl_cluster)
        self.edt_cluster = QtGui.QLineEdit(AddNeuronDialog)
        self.edt_cluster.setText("")
        self.edt_cluster.setObjectName("edt_cluster")
        self.lo_form0_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.edt_cluster)
        self.lbl_name = QtGui.QLabel(AddNeuronDialog)
        self.lbl_name.setObjectName("lbl_name")
        self.lo_form0_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_name)
        self.edt_name = QtGui.QLineEdit(AddNeuronDialog)
        self.edt_name.setObjectName("edt_name")
        self.lo_form0_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.edt_name)
        self.lo_vert0.addLayout(self.lo_form0_2)
        self.bbox_dialog = QtGui.QDialogButtonBox(AddNeuronDialog)
        self.bbox_dialog.setStandardButtons(QtGui.QDialogButtonBox.Abort|QtGui.QDialogButtonBox.Save)
        self.bbox_dialog.setCenterButtons(True)
        self.bbox_dialog.setObjectName("bbox_dialog")
        self.lo_vert0.addWidget(self.bbox_dialog)
        self.lbl_position.setBuddy(self.edt_position)
        self.lbl_orientation.setBuddy(self.edt_orientation)
        self.lbl_data.setBuddy(self.cb_data)
        self.lbl_frate.setBuddy(self.edt_frate)
        self.lbl_ampl.setBuddy(self.edt_ampl)

        self.retranslateUi(AddNeuronDialog)
        QtCore.QObject.connect(self.bbox_dialog, QtCore.SIGNAL("accepted()"), AddNeuronDialog.accept)
        QtCore.QObject.connect(self.bbox_dialog, QtCore.SIGNAL("rejected()"), AddNeuronDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddNeuronDialog)
        AddNeuronDialog.setTabOrder(self.edt_name, self.edt_position)
        AddNeuronDialog.setTabOrder(self.edt_position, self.edt_orientation)
        AddNeuronDialog.setTabOrder(self.edt_orientation, self.cb_data)
        AddNeuronDialog.setTabOrder(self.cb_data, self.edt_frate)
        AddNeuronDialog.setTabOrder(self.edt_frate, self.edt_ampl)
        AddNeuronDialog.setTabOrder(self.edt_ampl, self.edt_cluster)
        AddNeuronDialog.setTabOrder(self.edt_cluster, self.bbox_dialog)

    def retranslateUi(self, AddNeuronDialog):
        AddNeuronDialog.setWindowTitle(QtGui.QApplication.translate("AddNeuronDialog", "Add Neuron", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_position.setText(QtGui.QApplication.translate("AddNeuronDialog", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.edt_position.setToolTip(QtGui.QApplication.translate("AddNeuronDialog", "Enter the 3-dimensional scene position as a whitespace seperated sequence \"x, y, z\". E.g. \"10.0 15.0 25.666\" (Default= [0, 0, 0])", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_orientation.setText(QtGui.QApplication.translate("AddNeuronDialog", "Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.edt_orientation.setToolTip(QtGui.QApplication.translate("AddNeuronDialog", "Enter the 3-dimensional orientation vector as a whitespace seperated sequence (x, y, z). Also True gives a random orientation and False will ignore orientation. E.g. \"1.0 0.0 0.0\" (Default=False)", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_data.setText(QtGui.QApplication.translate("AddNeuronDialog", "Data:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_data.setToolTip(QtGui.QApplication.translate("AddNeuronDialog", "Choose a NeuronData instance for this neuron. IF there are no NeuronData in the list add them first!", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_frate.setText(QtGui.QApplication.translate("AddNeuronDialog", "Firing Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.edt_frate.setToolTip(QtGui.QApplication.translate("AddNeuronDialog", "Enter the firing rate in Hertz as a float. E.g. \"15.0\" (Default=10.0)", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_ampl.setText(QtGui.QApplication.translate("AddNeuronDialog", "Amplitude", None, QtGui.QApplication.UnicodeUTF8))
        self.edt_ampl.setToolTip(QtGui.QApplication.translate("AddNeuronDialog", "Enter an independent scaling factor for the amplitude as a float. E.g. \"1.0\" (Default=1.0)", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_cluster.setToolTip(QtGui.QApplication.translate("AddNeuronDialog", "The index of the cluster this neuron will belong to as an integer. E.g \"1\" (Default=0)", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_cluster.setText(QtGui.QApplication.translate("AddNeuronDialog", "Cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.edt_cluster.setToolTip(QtGui.QApplication.translate("AddNeuronDialog", "The index of the cluster the neuron will belong to as an interger. E.g. \"1\" (Default=0)", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_name.setText(QtGui.QApplication.translate("AddNeuronDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.edt_name.setToolTip(QtGui.QApplication.translate("AddNeuronDialog", "Optional name for the neuron as a string. E.g. \"Neuron A\"", None, QtGui.QApplication.UnicodeUTF8))

