# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multi_electrode_client.ui'
#
# Created: Tue Aug 24 17:42:49 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MultiElectrodeClient(object):
    def setupUi(self, MultiElectrodeClient):
        MultiElectrodeClient.setObjectName("MultiElectrodeClient")
        MultiElectrodeClient.resize(550, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/neural_sim_client.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MultiElectrodeClient.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MultiElectrodeClient)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.posi_gb = QtGui.QGroupBox(self.centralwidget)
        self.posi_gb.setObjectName("posi_gb")
        self.gridLayout = QtGui.QGridLayout(self.posi_gb)
        self.gridLayout.setObjectName("gridLayout")
        self.posi_lbl_target = QtGui.QLabel(self.posi_gb)
        self.posi_lbl_target.setFrameShape(QtGui.QFrame.Box)
        self.posi_lbl_target.setObjectName("posi_lbl_target")
        self.gridLayout.addWidget(self.posi_lbl_target, 0, 0, 1, 1)
        self.posi_edit_target = QtGui.QLineEdit(self.posi_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posi_edit_target.sizePolicy().hasHeightForWidth())
        self.posi_edit_target.setSizePolicy(sizePolicy)
        self.posi_edit_target.setMinimumSize(QtCore.QSize(80, 0))
        self.posi_edit_target.setObjectName("posi_edit_target")
        self.gridLayout.addWidget(self.posi_edit_target, 0, 1, 1, 1)
        self.posi_btn_go = QtGui.QToolButton(self.posi_gb)
        self.posi_btn_go.setObjectName("posi_btn_go")
        self.gridLayout.addWidget(self.posi_btn_go, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(47, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        self.posi_lbl_position = QtGui.QLabel(self.posi_gb)
        self.posi_lbl_position.setFrameShape(QtGui.QFrame.Box)
        self.posi_lbl_position.setObjectName("posi_lbl_position")
        self.gridLayout.addWidget(self.posi_lbl_position, 0, 6, 1, 1)
        self.posi_edit_position = QtGui.QLineEdit(self.posi_gb)
        self.posi_edit_position.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posi_edit_position.sizePolicy().hasHeightForWidth())
        self.posi_edit_position.setSizePolicy(sizePolicy)
        self.posi_edit_position.setMinimumSize(QtCore.QSize(80, 0))
        self.posi_edit_position.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.posi_edit_position.setReadOnly(True)
        self.posi_edit_position.setObjectName("posi_edit_position")
        self.gridLayout.addWidget(self.posi_edit_position, 0, 7, 1, 1)
        self.posi_slider_target = QtGui.QSlider(self.posi_gb)
        self.posi_slider_target.setMinimumSize(QtCore.QSize(300, 0))
        self.posi_slider_target.setMaximum(1000)
        self.posi_slider_target.setPageStep(25)
        self.posi_slider_target.setProperty("value", 0)
        self.posi_slider_target.setTracking(False)
        self.posi_slider_target.setOrientation(QtCore.Qt.Horizontal)
        self.posi_slider_target.setTickPosition(QtGui.QSlider.TicksBelow)
        self.posi_slider_target.setTickInterval(25)
        self.posi_slider_target.setObjectName("posi_slider_target")
        self.gridLayout.addWidget(self.posi_slider_target, 1, 0, 1, 8)
        self.posi_slider_position = QtGui.QSlider(self.posi_gb)
        self.posi_slider_position.setEnabled(False)
        self.posi_slider_position.setMinimumSize(QtCore.QSize(300, 0))
        self.posi_slider_position.setMaximum(1000)
        self.posi_slider_position.setPageStep(25)
        self.posi_slider_position.setTracking(False)
        self.posi_slider_position.setOrientation(QtCore.Qt.Horizontal)
        self.posi_slider_position.setTickPosition(QtGui.QSlider.TicksBelow)
        self.posi_slider_position.setTickInterval(25)
        self.posi_slider_position.setObjectName("posi_slider_position")
        self.gridLayout.addWidget(self.posi_slider_position, 2, 0, 1, 8)
        self.posi_btn_request = QtGui.QToolButton(self.posi_gb)
        self.posi_btn_request.setObjectName("posi_btn_request")
        self.gridLayout.addWidget(self.posi_btn_request, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.posi_gb)
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 532, 385))
        self.page.setObjectName("page")
        self.toolBox.addItem(self.page, "")
        self.verticalLayout.addWidget(self.toolBox)
        MultiElectrodeClient.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MultiElectrodeClient)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MultiElectrodeClient.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MultiElectrodeClient)
        self.statusbar.setObjectName("statusbar")
        MultiElectrodeClient.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MultiElectrodeClient)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.posi_lbl_target.setBuddy(self.posi_edit_target)
        self.posi_lbl_position.setBuddy(self.posi_edit_position)

        self.retranslateUi(MultiElectrodeClient)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("activated()"), MultiElectrodeClient.close)
        QtCore.QObject.connect(self.posi_edit_target, QtCore.SIGNAL("returnPressed()"), self.posi_btn_go.click)
        QtCore.QMetaObject.connectSlotsByName(MultiElectrodeClient)
        MultiElectrodeClient.setTabOrder(self.posi_edit_target, self.posi_btn_go)
        MultiElectrodeClient.setTabOrder(self.posi_btn_go, self.posi_btn_request)
        MultiElectrodeClient.setTabOrder(self.posi_btn_request, self.posi_edit_position)
        MultiElectrodeClient.setTabOrder(self.posi_edit_position, self.posi_slider_target)
        MultiElectrodeClient.setTabOrder(self.posi_slider_target, self.posi_slider_position)

    def retranslateUi(self, MultiElectrodeClient):
        MultiElectrodeClient.setWindowTitle(QtGui.QApplication.translate("MultiElectrodeClient", "Multi Electrode Client", None, QtGui.QApplication.UnicodeUTF8))
        self.posi_gb.setTitle(QtGui.QApplication.translate("MultiElectrodeClient", "Multi-Electrode Position Controll", None, QtGui.QApplication.UnicodeUTF8))
        self.posi_lbl_target.setText(QtGui.QApplication.translate("MultiElectrodeClient", "TARGET [µm]", None, QtGui.QApplication.UnicodeUTF8))
        self.posi_edit_target.setText(QtGui.QApplication.translate("MultiElectrodeClient", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.posi_btn_go.setToolTip(QtGui.QApplication.translate("MultiElectrodeClient", "send to position", None, QtGui.QApplication.UnicodeUTF8))
        self.posi_btn_go.setText(QtGui.QApplication.translate("MultiElectrodeClient", "!", None, QtGui.QApplication.UnicodeUTF8))
        self.posi_lbl_position.setText(QtGui.QApplication.translate("MultiElectrodeClient", "POSTION [µm]", None, QtGui.QApplication.UnicodeUTF8))
        self.posi_edit_position.setText(QtGui.QApplication.translate("MultiElectrodeClient", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.posi_btn_request.setToolTip(QtGui.QApplication.translate("MultiElectrodeClient", "request current position", None, QtGui.QApplication.UnicodeUTF8))
        self.posi_btn_request.setText(QtGui.QApplication.translate("MultiElectrodeClient", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("MultiElectrodeClient", "Page 1", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MultiElectrodeClient", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MultiElectrodeClient", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MultiElectrodeClient", "Alt+Q", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
