# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multi_electrode_client.ui'
#
# Created: Tue Aug 24 15:01:22 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MultiElectrodeClient(object):
    def setupUi(self, MultiElectrodeClient):
        MultiElectrodeClient.setObjectName("MultiElectrodeClient")
        MultiElectrodeClient.resize(505, 232)
        self.centralwidget = QtGui.QWidget(MultiElectrodeClient)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.posi_gb = QtGui.QGroupBox(self.centralwidget)
        self.posi_gb.setObjectName("posi_gb")
        self.gridLayout = QtGui.QGridLayout(self.posi_gb)
        self.gridLayout.setObjectName("gridLayout")
        self.posi_lbl_target = QtGui.QLabel(self.posi_gb)
        self.posi_lbl_target.setFrameShape(QtGui.QFrame.Box)
        self.posi_lbl_target.setObjectName("posi_lbl_target")
        self.gridLayout.addWidget(self.posi_lbl_target, 0, 0, 1, 1)
        self.posi_lcd_target = QtGui.QLCDNumber(self.posi_gb)
        self.posi_lcd_target.setFrameShape(QtGui.QFrame.Panel)
        self.posi_lcd_target.setNumDigits(7)
        self.posi_lcd_target.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.posi_lcd_target.setObjectName("posi_lcd_target")
        self.gridLayout.addWidget(self.posi_lcd_target, 0, 1, 1, 1)
        self.posi_slider_target = QtGui.QSlider(self.posi_gb)
        self.posi_slider_target.setMinimumSize(QtCore.QSize(300, 0))
        self.posi_slider_target.setMaximum(1000)
        self.posi_slider_target.setPageStep(25)
        self.posi_slider_target.setProperty("value", 0)
        self.posi_slider_target.setOrientation(QtCore.Qt.Horizontal)
        self.posi_slider_target.setTickPosition(QtGui.QSlider.TicksBelow)
        self.posi_slider_target.setTickInterval(20)
        self.posi_slider_target.setObjectName("posi_slider_target")
        self.gridLayout.addWidget(self.posi_slider_target, 0, 2, 1, 1)
        self.posi_lbl_position = QtGui.QLabel(self.posi_gb)
        self.posi_lbl_position.setFrameShape(QtGui.QFrame.Box)
        self.posi_lbl_position.setObjectName("posi_lbl_position")
        self.gridLayout.addWidget(self.posi_lbl_position, 1, 0, 1, 1)
        self.posi_lcd_position = QtGui.QLCDNumber(self.posi_gb)
        self.posi_lcd_position.setFrameShape(QtGui.QFrame.Panel)
        self.posi_lcd_position.setNumDigits(7)
        self.posi_lcd_position.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.posi_lcd_position.setObjectName("posi_lcd_position")
        self.gridLayout.addWidget(self.posi_lcd_position, 1, 1, 1, 1)
        self.posi_slider_position = QtGui.QSlider(self.posi_gb)
        self.posi_slider_position.setEnabled(False)
        self.posi_slider_position.setMinimumSize(QtCore.QSize(300, 0))
        self.posi_slider_position.setMaximum(1000)
        self.posi_slider_position.setPageStep(25)
        self.posi_slider_position.setOrientation(QtCore.Qt.Horizontal)
        self.posi_slider_position.setTickPosition(QtGui.QSlider.TicksBelow)
        self.posi_slider_position.setTickInterval(20)
        self.posi_slider_position.setObjectName("posi_slider_position")
        self.gridLayout.addWidget(self.posi_slider_position, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.posi_gb)
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 487, 45))
        self.page.setObjectName("page")
        self.toolBox.addItem(self.page, "")
        self.verticalLayout.addWidget(self.toolBox)
        MultiElectrodeClient.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MultiElectrodeClient)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 505, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MultiElectrodeClient.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MultiElectrodeClient)
        self.statusbar.setObjectName("statusbar")
        MultiElectrodeClient.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MultiElectrodeClient)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MultiElectrodeClient)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.posi_slider_position, QtCore.SIGNAL("sliderMoved(int)"), self.posi_lcd_position.display)
        QtCore.QObject.connect(self.posi_slider_target, QtCore.SIGNAL("sliderMoved(int)"), self.posi_lcd_target.display)
        QtCore.QMetaObject.connectSlotsByName(MultiElectrodeClient)

    def retranslateUi(self, MultiElectrodeClient):
        MultiElectrodeClient.setWindowTitle(QtGui.QApplication.translate("MultiElectrodeClient", "Multi Electrode Client", None, QtGui.QApplication.UnicodeUTF8))
        self.posi_gb.setTitle(QtGui.QApplication.translate("MultiElectrodeClient", "Multi-Electrode Position Controll", None, QtGui.QApplication.UnicodeUTF8))
        self.posi_lbl_target.setText(QtGui.QApplication.translate("MultiElectrodeClient", "TARGET   [µm]", None, QtGui.QApplication.UnicodeUTF8))
        self.posi_lbl_position.setText(QtGui.QApplication.translate("MultiElectrodeClient", "POSTION [µm]", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("MultiElectrodeClient", "Page 1", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MultiElectrodeClient", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MultiElectrodeClient", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MultiElectrodeClient", "Alt+Q", None, QtGui.QApplication.UnicodeUTF8))

